# Generated by Django 2.1.2 on 2018-11-25 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 25, 17, 52, 22, 64159, tzinfo=utc))),
                ('page_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Pages', unique=True)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
