# Generated by Django 2.1.2 on 2018-11-25 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 25, 17, 52, 24, 992607, tzinfo=utc)),
        ),
    ]
