# Generated by Django 2.1.2 on 2018-11-25 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181125_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='assignment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 25, 19, 57, 43, 356858, tzinfo=utc)),
        ),
    ]
